package main

import (
	"embed"
	"fmt"
	"os"
	"path/filepath"

	"sb3topy/converter"
)

//go:embed all:engine
var engineFS embed.FS

//go:embed specmap_data.json
var specmapData []byte

func main() {
	args := os.Args[1:]

	if len(args) == 0 || args[0] == "-h" || args[0] == "--help" || args[0] == "/?" {
		printUsage()
		os.Exit(0)
	}

	var err error
	switch args[0] {
	case "inspect":
		err = runInspect(args[1:], os.Stdout, os.Stderr)
	case "to-python":
		if len(args) < 2 {
			printUsage()
			os.Exit(2)
		}
		err = runToPython(args[1:])
	case "to-sb3", "reverse":
		if len(args) < 2 {
			printUsage()
			os.Exit(2)
		}
		var output string
		if len(args) >= 3 {
			output = args[2]
		}
		err = converter.Reverse(converter.ReverseOptions{
			ProjectPath: args[1],
			OutputSB3:   output,
			SpecmapData: specmapData,
		})
	case "verify":
		if len(args) < 2 {
			printUsage()
			os.Exit(2)
		}
		err = converter.VerifyRoundTripProject(args[1], specmapData)
		if err == nil {
			fmt.Println("Verification passed: project.py, canonical Scratch JSON, metadata, block graph, and assets are consistent")
		}
	case "sync":
		if len(args) < 2 {
			printUsage()
			os.Exit(2)
		}
		err = converter.SyncRoundTripProject(args[1], specmapData)
		if err == nil {
			fmt.Println("Sync completed: project.py was regenerated from .sb3topy/project.json")
		}
	default:
		// Backward-compatible form: sb3topy game.sb3 [output-dir]
		err = runToPython(args)
	}

	if err != nil {
		fmt.Fprintf(os.Stderr, "\nOperation failed: %v\n", err)
		os.Exit(1)
	}
}

func runToPython(args []string) error {
	sb3Path := args[0]
	var outputDir string
	if len(args) >= 2 {
		outputDir = args[1]
	}

	if _, err := os.Stat(sb3Path); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("SB3 file not found: %q", sb3Path)
		}
		return fmt.Errorf("cannot access SB3 file %q: %w", sb3Path, err)
	}

	opts := converter.ConvertOptions{
		SB3Path:     sb3Path,
		OutputDir:   outputDir,
		EngineFS:    engineFS,
		SpecmapData: specmapData,
	}
	return converter.Run(opts)
}

func printUsage() {
	appName := filepath.Base(os.Args[0])
	fmt.Printf(`sb3topy CLI - reversible Scratch 3 (.sb3) and Python debugging workflow

Usage:
  %[1]s <project.sb3> [output-directory]       # Legacy form; equivalent to to-python
  %[1]s to-python <project.sb3> [output-directory]
  %[1]s inspect [--json] [--target NAME] [--block ID] <project.sb3|workspace|project.py>
  %[1]s verify <workspace|project.py>
  %[1]s sync <workspace|project.py>
  %[1]s to-sb3 <workspace|project.py> [output.sb3]

Recommended agent workflow:
  1. %[1]s inspect --json game.sb3
  2. %[1]s to-python game.sb3 ./work/game
  3. %[1]s verify ./work/game
  4. Analyze project.py and inspect --json --block BLOCK_ID ./work/game
  5. Apply reversible edits to work/game/.sb3topy/project.json
  6. %[1]s sync ./work/game
  7. %[1]s verify ./work/game
  8. %[1]s to-sb3 ./work/game repaired.sb3
  9. Explain the change to the student and test repaired.sb3 in Scratch.

Important:
  Arbitrary Python cannot be reliably decompiled into Scratch blocks.
  to-sb3 only accepts a reversible workspace generated by this tool when
  project.py and .sb3topy/project.json pass verification. This prevents
  silent loss of edits and avoids producing misleading SB3 output.
`, appName)
}
